name: build

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - windows-latest
                    - macos-latest
                    - ubuntu-latest
            max-parallel: 1
            fail-fast: false
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16.14.2 # use the latest LTS version of Node
            - name: Install dependencies
              run: npm install
            - name: Build app
              if: github.ref != 'refs/heads/main'
              run: npm build
            - name: Build & deploy app
              if: github.ref == 'refs/heads/main'
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npm release
